/*
 * This Java source file was generated by the Gradle 'init' task.
 */
import org.junit.Test;
import static org.junit.Assert.*;
import org.snobotics.NetworkTable.Monitor;
import edu.wpi.first.networktables.NetworkTableInstance;

public class TestMonitor {
    @Test public void testAppHasAGreeting() {
        return;
//        Monitor.main(new String[]{""});
//        Monitor classUnderTest = new Monitor();
//        assertNotNull("app should have a greeting", classUnderTest.getGreeting());
    }
}
