/*
 * This Java source file was generated by the Gradle 'init' task.
 */
import org.junit.Test;
import static org.junit.Assert.*;
import org.snobotics.NetworkTable.Monitor;

public class TestNetworkTable {
    @Test public void testAppHasAGreeting() {
        Monitor classUnderTest = new Monitor();
        assertNotNull("app should have a greeting", classUnderTest.getGreeting());
    }
}
